#!/bin/bash
#################################################################################################################

# Specify colors utilized in the terminal
normal=$(tput sgr0)              # White
red=$(tput setaf 1)              # Red
green=$(tput setaf 2)            # Green
yellow=$(tput setaf 3)           # Yellow
blue=$(tput setaf 21)            # Blue
violet=$(tput setaf 5)           # Violet
cyan=$(tput setaf 6)             # Cyan
white=$(tput setaf 7)            # White
bldred=${txtbld}$(tput setaf 1)  # Bold Red
bldgrn=${txtbld}$(tput setaf 2)  # Bold Green
bldblu=${txtbld}$(tput setaf 4)  # Bold Blue
bldylw=${txtbld}$(tput setaf 3)  # Bold Yellow
bldvlt=${txtbld}$(tput setaf 5)  # Bold Violet
bldcya=${txtbld}$(tput setaf 6)  # Bold Cyan
bldwht=${txtbld}$(tput setaf 7)  # Bold White
blink=$(tput blink)              # Blink
bold=$(tput bold)                # Bold
reverse=$(tput smso)		 # Reverse Colors
underline=$(tput smul)           # Underline

#################################################################################################################

COL="${bold}${blue}"
COL_RESET="\x1b[39;49;00m"

echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"##########                                                             ##########"
echo -e $COL"##########  ########  ######## ##     ## ######## ########   #######   ##########"
echo -e $COL"##########  ##     ## ##        ##   ##     ##    ##     ## ##     ##  ##########"
echo -e $COL"##########  ##     ## ##         ## ##      ##    ##     ## ##     ##  ##########"
echo -e $COL"##########  ##     ## ######      ###       ##    ########  ##     ##  ##########"
echo -e $COL"##########  ##     ## ##         ## ##      ##    ##   ##   ##     ##  ##########"
echo -e $COL"##########  ##     ## ##        ##   ##     ##    ##    ##  ##     ##  ##########"
echo -e $COL"##########  ########  ######## ##     ##    ##    ##     ##  #######   ##########"
echo -e $COL"##########                                                             ##########"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"##########                                                             ##########"
echo -e $COL"##########   $red "WARNING: Dextroamphetamine is a CPU stimulant!"        $COL   ##########"
echo -e $COL"##########   $red "WARNING: Dextroamphetamine may cause dizziness!"       $COL   ##########"
echo -e $COL"##########   $red "WARNING: Dextroamphetamine may cause sleeplessness!"   $COL   ##########"
echo -e $COL"##########   $red "WARNING: Dextroamphetamine is to be used only by you!" $COL   ##########"
echo -e $COL"##########   $red "WARNING: Use Dextroamphetamine with extreme caution!"  $COL   ##########"
echo -e $COL"##########                                                             ##########"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"
echo -e $COL"#################################################################################"

#################################################################################################################

echo -e "Select Device to Build"
PS3='Build: '
options=("Nexus 6P" "Galaxy S4" "Quit")
select opt in "${options[@]}"
do
    case $opt in
        "Nexus 6P")
            echo "Building Nexus 6P ROM"
	    cd ${HOME}/RR
	    make clobber
	    make clean
	    time repo sync --force-broken --force-sync --no-clone-bundle --quiet
	    export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx15g"
	    ./prebuilts/sdk/tools/jack-admin kill-server
	    ./prebuilts/sdk/tools/jack-admin start-server
	    . build/envsetup.sh 
	    brunch angler
            ;;
        "Galaxy S4")
            echo "Building Galaxy S4 ROM"
	    cd ${HOME}/RR
	    make clobber
            make clean
            time repo sync --force-broken --force-sync --no-clone-bundle --quiet
            export JACK_SERVER_VM_ARGUMENTS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx15g"
            ./prebuilts/sdk/tools/jack-admin kill-server
   	    ./prebuilts/sdk/tools/jack-admin start-server
            . build/envsetup.sh 
            breakfast jfltespr
            mka bacon
            ;;
        "Quit")
            break
            ;;
        *) echo invalid option;;
    esac
done

#################################################################################################################

